### ISSUE TITLE
Update new stats chart to allow CORS

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#2179]
### Description

accessing https://stats.dev.grid.tf/api/stats-summary from playground throws cors errors 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/d412c778-def7-46b5-ab40-573d18b80e7f)

need to update ingress values to allow get method from all origins

**Comment by PeterNashaat** [comment]
- you can update the Nginx Ingress template to include CORS-related annotations. This will allow requests from all origins. Here's an example of how you might configure it : 
```
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
s
```
- or it can be 
```
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
```
